/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jni_yh_com_jnidemo_AndroidJni */

#ifndef _Included_jni_yh_com_jnidemo_AndroidJni
#define _Included_jni_yh_com_jnidemo_AndroidJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jni_yh_com_jnidemo_AndroidJni
 * Method:    getHelloWordText
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jni_yh_com_jnidemo_AndroidJni_getHelloWordText
  (JNIEnv *, jobject);

/*
 * Class:     jni_yh_com_jnidemo_AndroidJni
 * Method:    setUserName
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jni_yh_com_jnidemo_AndroidJni_setUserName
  (JNIEnv *, jobject, jstring);

/*
 * Class:     jni_yh_com_jnidemo_AndroidJni
 * Method:    getResult
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_jni_yh_com_jnidemo_AndroidJni_getResult
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
